### ISSUE TITLE
History when hitting the reload button

### ISSUE THREAD

**Issue by krystofbe** [tuvistavie/plug-navigation-history#5]
Thanks for this awesome lib <3
I'm using `NavigationHistory.last_path(conn, 1)` to return to the second last visited path. This works perfectly, even if submitting forms.

I have encountered, that hitting the reload button of the browser adds the current path again to the last pathes. I then looks like this
```
last_paths = 
["/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit",
 "/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit",
 "/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit",
 "/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit",
 "/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit",
 "/user/1c5f73ce-66bf-4f55-9155-e556fac86d42/edit", "/search" ]
```

depending on how much i hit `reload`.

Any idea how to avoid this behavior and add each route uniquely?

**Comment by augnustin** [comment]
:+1: 

This doesn't make much sense to store multiple times the same URL. It shall be super easy to change actually, I may go for the PR if the author agrees.

This should at least be an option, but I would suggest the default is to remove doublons.

Also there could be a mode where query strings are ignored in the doublon consideration, but that's more subtle.

**Comment by krystofbe** [comment]
Thanks for your feedback @augnustin! I'm using my own fork with this change already, I'd love to open a PR with the change if @danhper agrees!

**Comment by augnustin** [comment]
Sounds interesting.

How come on your fork, there *isn't anything to compare*: https://github.com/danhper/plug-navigation-history/compare/master...krystofbe:master ?

**Comment by krystofbe** [comment]
It's not on master:
https://github.com/danhper/plug-navigation-history/compare/master...krystofbe:fix-reloading
